version: "3"
services:
  # Web service layer
  nginx:
    image: nginx:alpine
    volumes:
      - "./app:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8000:80"
    depends_on:
      - php
    restart: always

  # Application service layer
  php:
    image: php:fpm
    volumes:
      - "./app:/var/www/html"
    ports:
      - "9000:9000"
    restart: always

  # Composer
  composer:
    image: composer:latest
    volumes:
      - "./app:/app"
    depends_on:
      - nginx
    command: "composer install"
    command: "composer require --ignore-platform-reqs jacwright/restserver"
